### ISSUE TITLE
Robot does not navigate to goal set by Nav2 

### ISSUE THREAD

**Issue by immanueln98** [clearpathrobotics/clearpath_nav2_demos#12]
Description: The robot is not navigating along the path to the goal generated by Nav2. The controller server consistently logs the following message, even though the robot doesn't seem to move towards the goal:

`[controller_server-1] [INFO] [1726063070.158009741] [a200_0000.controller_server]: Passing new path to controller.`

   

-  OS: Ubuntu 22.04
-     ROS 2 Distro: Humble
-     Built from source or installed: Installed
-     Package version:  0.2.7-1jammy.20240408.173915
-     Real hardware or simulation: Simulation

Expected behaviour The robot should follow the path provided by Nav2 and reach the goal as per the generated navigation plan.

Actual behaviour Despite the controller logging the receipt of the new path, the robot does not navigate towards the goal. It remains stationary, with no visible attempts to follow the path.

To Reproduce Steps to reproduce:

-     Launch the simulation environment.
-     Set a goal using Nav2.
-     Observe the robot's lack of movement while the controller logs that a new path has been passed.

Other notes

-     All testing was done in simulation using Ubuntu 22.04, ROS 2 Humble, and the simulator package installed from the latest repository version.
-     I've followed the standard steps in launching the demo and setting goals but still encounter this issue.
-

**Comment by immanueln98** [comment]
Hi @tonybaltovski, so you happen to know what the issue could be?

**Comment by tonybaltovski** [comment]
@immanueln98 my apologies for the delay.  Did you solve this?  The version you pointed out is out dated.  Can you try `1.0` if you are still having issues?
