### ISSUE TITLE
Nav2 bringup Can not find odom to bae_link transform and Rviz can not receive the map being published

### ISSUE THREAD

**Issue by immanueln98** [clearpathrobotics/clearpath_nav2_demos#7]
**Please provide the following information:**
 - OS: Ubuntu 22.04
 - ROS 2 Distro:  Humble
 - Built from source or installed: Installed
 - Package version: `Package: ros-humble-clearpath-common
                                  Status: install ok installed
                                  Priority: optional
                                  Section: misc
                                  Installed-Size: 41
                                  Maintainer: Luis Camero <lcamero@clearpathrobotics.com>
                                  Architecture: amd64
                                  Version: 0.1.2-1jammy.20231002.212915
                                  Depends: ros-humble-clearpath-control, ros-humble-clearpath-description, ros-humble-clearpath-generator-common, ros-humble-clearpath-platform, ros-humble-ros-workspace
                                  Description: Clearpath Common Metapackage
                                  `
 - Real hardware or simulation: Simulation

 **Expected behaviour**
The husky should be able to carry out navigation tasks upon request.

 **Actual behaviour**
After following the required steps presented in the docs, Rviz seems to have trouble reading the robot model and reading the map despite it being displayed as shown in the image below.
![Screenshot from 2023-10-09 13-31-30](https://github.com/clearpathrobotics/clearpath_nav2_demos/assets/87979664/c89a61aa-2d7e-4981-99b5-99843157b794)
![Screenshot from 2023-10-09 13-31-18](https://github.com/clearpathrobotics/clearpath_nav2_demos/assets/87979664/bffcaaf2-34a6-4cd0-abbe-8f342d6130c1)
The terminal on the top left is gazebo's output. Bottom left is rviz and the bottom right is the localisation package. Appropriate setup_paths and namespaces were used.

**To Reproduce**
Follow steps laid out in the Navigation Demos:Localization docs

**Other notes**
A side note with regards to the map, I had noticed after careful inspection of the topics being published that the map topic is `/a200_0000/map`, however, rviz does not allow a `/` as the first character of the fixed frame under global options.

**Comment by luis-camero** [comment]
Have you started the simulation in Gazebo? i.e. pressing the play button at the bottom left corner in the Gazebo window.

**Comment by immanueln98** [comment]
Oh I had not taken that into account my apologies. It does work now. However I am trying to publish poses to the nav stack using the simple commander Nav 2 API but it is still waiting for "amcl/get_state_service" despite the nav bring up running. Do you perhaps know why this is the case?  
![Screenshot from 2023-10-27 11-16-49](https://github.com/clearpathrobotics/clearpath_nav2_demos/assets/87979664/5ed68b36-c688-47c7-9d8c-8593f706a248)

**Comment by immanueln98** [comment]
I just observed the services that are running and state service that is available has the robot's namespace infront of it. I believe that is the reason the basic navigator cannot find it. Do you perhaps know how to point the basic navigator to the correct service
![Screenshot from 2023-10-27 12-18-12](https://github.com/clearpathrobotics/clearpath_nav2_demos/assets/87979664/02bb865a-d017-45be-9ab9-a84155c7a4b4)

**Comment by immanueln98** [comment]
I figured it out! I will close this ticket now. Thanks for the help

**Comment by KushnirDmytro** [comment]
> I figured it out! I will close this ticket now. Thanks for the help

People would be gratefull for the comments on what was the issue. Mistakes can be repeated 😓
