### ISSUE TITLE
Running on a Physical Robot

### ISSUE THREAD

**Issue by immanueln98** [clearpathrobotics/clearpath_nav2_demos#8]
Hi there. 
I would like to request a tutorial on how to run the nav2 demo's on a physical robot. The docs say that it will work but do not go in depth as to how that will work or look like. 

I am currently trying out the Nav2 demo on a A200 Husky but cannot get it to work due to missing a transform from base_link to map while using the provided warehouse map.

**Comment by roni-kreinin** [comment]
The warehouse map is intended to be used for the simulated warehouse world. If you are running these on a physical robot, you will have to create a map of the environment.

The first step is to run [SLAM](https://docs.clearpathrobotics.com/docs/ros/tutorials/navigation_demos/slam). Assuming the robot is up and running, launch the RViz on your PC with:
```
ros2 launch clearpath_viz view_navigation.launch.py namespace:=<your_robot_namespace>
```
Then, launch SLAM on the robot:
```
ros2 launch clearpath_nav2_demos slam.launch.py
```
You should see a map starting to generate (assuming your A200 has a 2d lidar).

Next, [drive](https://docs.clearpathrobotics.com/docs/ros/tutorials/driving/) the robot around until the map is filled out for your environment. Then save the map on the robot PC by calling:
```
ros2 run nav2_map_server map_saver_cli -f "map_name" \
--ros-args -p map_subscribe_transient_local:=true -r __ns:=<your_robot_namespace>
```

Now you can stop SLAM and launch localization with your new map:

```
ros2 launch clearpath_nav2_demos localization.launch.py map:=/path/to/my/map.yaml
```
Then, in another terminal, launch Nav2:
```
ros2 launch clearpath_nav2_demos nav2.launch.py
```

**Comment by immanueln98** [comment]
Hi Roni

I tried launching the SLAM toolbox but I keep getting an error. SLAM is unable to load the libceres_solver_plugin.so as shown in the terminal output below.
![image](https://github.com/clearpathrobotics/clearpath_nav2_demos/assets/87979664/d6ea2c03-a80a-44fb-a400-d1ed7114907d)

**Comment by immanueln98** [comment]
Good Day, any idea what could be the issue if you have come across such a bug?

**Comment by roni-kreinin** [comment]
@immanueln98 Try running `sudo apt update && sudo apt upgrade` to update all of your packages. You may have a version mismatch in some of the `slam_toolbox` packages.

**Comment by immanueln98** [comment]
I tried that and it still results in the same error

**Comment by tonybaltovski** [comment]
@immanueln98 that is a linker error from `slam_toolbox`.  You should open an issue there and provide the version of the binary you are using.

**Comment by immanueln98** [comment]
Hi Tony. I had already did as shown in the following link: https://github.com/SteveMacenski/slam_toolbox/issues/649

Steve seems to not be able to reproduce the problem and mentions it could be an incompatible dependency somewhere. Does the slam toolbox run correctly on your platform?

**Comment by immanueln98** [comment]
I managed to figure out the underlying issue. 
When upgrading from ubuntu 20.04 to 22.04 in order to use humble, the SLAM package will throw the error shown above. I carried out a fresh install of ubuntu and ros2 on the husky and the SLAM package worked!

**Comment by immanueln98** [comment]
I managed to figure out the underlying issue.
When upgrading from ubuntu 20.04 to 22.04 in order to use humble, the SLAM package will throw the error shown above. I carried out a fresh install of ubuntu and ros2 on the husky and the SLAM package worked!
